let shopItemsData = [{
  id: "ww1",
  name: "Birthday cake",
  price: 5000,
  desc: "This is the best birthday cake you would ever have",
  img: "img/cake1.jpg",
},
{
  id: "ww2",
  name: "Cake slice",
  price: 1000,
  desc: "This is the best birthday cake you would ever have",
  img: "img/cake2.jpg",
},
{
  id: "ww3",
  name: "Birthday cake",
  price: 7000,
  desc: "This is the best birthday cake you would ever have",
  img: "img/cake3.jpg",
},
{
  id: "ww4",
  name: "Birthday cake",
  price: 10000,
  desc: "This is the best birthday cake you would ever have",
  img: "img/cake4.jpg",
},
{
  id: "ww5",
  name: "Birthday cake",
  price: 10000,
  desc: "This is the best birthday cake you would ever have",
  img: "img/cake5.jpg",
},
{
  id: "ww6",
  name: "Birthday cake",
  price: 10000,
  desc: "This is the best birthday cake you would ever have",
  img: "img/cake6.jpg",
},
{
  id: "ww7",
  name: "Birthday cake",
  price: 10000,
  desc: "This is the best birthday cake you would ever have",
  img: "img/cake7.jpg",
},
{
  id: "ww8",
  name: "Birthday cake",
  price: 10000,
  desc: "This is the best birthday cake you would ever have",
  img: "img/cake8.jpg",
},
{
  id: "ww9",
  name: "Birthday cake",
  price: 10000,
  desc: "This is the best birthday cake you would ever have",
  img: "img/cake9.jpg",
},
{
  id: "ww10",
  name: "Birthday cake",
  price: 10000,
  desc: "This is the best birthday cake you would ever have",
  img: "img/cake10.jpg",
},
{
  id: "ww11",
  name: "Birthday cake",
  price: 10000,
  desc: "This is the best birthday cake you would ever have",
  img: "img/cake11.jpg",
},
{
  id: "ww12",
  name: "Birthday cake",
  price: 10000,
  desc: "This is the best birthday cake you would ever have",
  img: "img/cake12.jpg",
},
{
  id: "ww13",
  name: "Birthday cake",
  price: 10000,
  desc: "This is the best birthday cake you would ever have",
  img: "img/cake13.jpg",
},
{
  id: "ww14",
  name: "Birthday cake",
  price: 10000,
  desc: "This is the best birthday cake you would ever have",
  img: "img/cake14.jpg",
},
{
  id: "ww15",
  name: "Birthday cake",
  price: 10000,
  desc: "This is the best birthday cake you would ever have",
  img: "img/cake15.jpg",
},
{
  id: "ww16",
  name: "Birthday cake",
  price: 10000,
  desc: "This is the best birthday cake you would ever have",
  img: "img/cake16.jpg",
},
{
  id: "ww17",
  name: "Birthday cake",
  price: 10000,
  desc: "This is the best birthday cake you would ever have",
  img: "img/cake17.jpg",
},
{
  id: "ww18",
  name: "Birthday cake",
  price: 10000,
  desc: "This is the best birthday cake you would ever have",
  img: "img/cake18.jpg",
},
{
  id: "ww19",
  name: "Birthday cake",
  price: 10000,
  desc: "This is the best birthday cake you would ever have",
  img: "img/cake19.jpg",
},
{
  id: "ww20",
  name: "Birthday cake",
  price: 10000,
  desc: "This is the best birthday cake you would ever have",
  img: "img/cake20.jpg",
},
{
  id: "ww21",
  name: "Birthday cake",
  price: 10000,
  desc: "This is the best birthday cake you would ever have",
  img: "img/cake21.jpg",
},
{
  id: "ww22",
  name: "Birthday cake",
  price: 10000,
  desc: "This is the best birthday cake you would ever have",
  img: "img/cake22.jpg",
},
{
  id: "ww23",
  name: "Birthday cake",
  price: 10000,
  desc: "This is the best birthday cake you would ever have",
  img: "img/cake23.jpg",
},
{
  id: "ww24",
  name: "Birthday cake",
  price: 10000,
  desc: "This is the best birthday cake you would ever have",
  img: "img/cake24.jpg",
},
];